volumes:
  postgres-data:
  static-images:
  redis-data:

networks:
  rocket-net:

services:
  api-db:
    container_name: api-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rocket-net

  redis:
    image: redis:latest
    container_name: redis-rocket
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - rocket-net

  api:
    container_name: api
    image: api-rocket
    environment:
      PORT: ${API_PORT}
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      PRISMA_DATABASE_URL: ${PRISMA_DATABASE_URL}
      VIRTUAL_ID_SALT: ${VIRTUAL_ID_SALT}
      STATIC_IMAGES_PATH: ${STATIC_IMAGES_PATH}
    ports:
      - '3001:3001'
    depends_on:
      - api-db
    volumes:
      - ./src:/workspace/src
      - ./prisma:/workspace/prisma
      - static-images:${STATIC_IMAGES_PATH}
    networks:
      - rocket-net
    tty: true
