version: '3.9'

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:latest
    container_name: rocket-db
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
